services:
  sso-gmc-postgres:
    container_name: sso-gmc-postgres
    image: postgres:15
    env_file: .env
    volumes:
      - /docker-volumes/GMC/sso/postgres:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    networks:
      - gmc_network

  sso-gmc-redis:
    container_name: sso-gmc-redis
    image: redis/redis-stack:6.2.6-v5
    env_file: .env
    volumes:
      - /docker-volumes/GMC/sso/redis:/data
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - gmc_network

networks:
  gmc_network:
    name: gmc_network
    external: true