"""User: Add user table

Revision ID: 2cff390b4ccb
Revises: 
Create Date: 2025-04-17 15:42:58.345132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cff390b4ccb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False, comment='email of user'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='password'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    sa.UniqueConstraint('sid'),
    schema='users',
    comment='users module schema'
    )
    op.create_index(op.f('ix_users_user_email'), 'user', ['email'], unique=True, schema='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_email'), table_name='user', schema='users')
    op.drop_table('user', schema='users')
    # ### end Alembic commands ###
